import React from 'react'

function ProductPageSlider() {
  return (
    <div>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum iusto beatae perspiciatis aspernatur recusandae architecto! Quod, iste. Iure et corporis vitae est ullam possimus deleniti earum, fugit consequatur sint exercitationem alias nisi ipsa veritatis quam assumenda temporibus, sequi nihil tempore deserunt! Aliquam dicta ex repudiandae obcaecati, quasi, cum praesentium facilis, voluptatibus perferendis quae possimus debitis. A aut delectus impedit, inventore dolor tempore fuga dicta quidem facere consequatur vitae exercitationem eveniet ullam cumque non temporibus, cupiditate esse. Earum soluta suscipit dignissimos reprehenderit laudantium ipsam perspiciatis, blanditiis nesciunt id, corporis amet velit voluptatum deleniti odio assumenda aliquid recusandae autem facere? Ea, quae delectus. Aperiam ab soluta libero illo officia, ut dolorum adipisci, cum tempore aliquam perferendis porro iste hic iure deleniti? Facilis autem veritatis odit illo eligendi molestiae beatae aliquid facere! Quae libero eum eveniet consequuntur quam quidem, corrupti repellat culpa corporis sequi. Corporis expedita eum cum facilis nisi in obcaecati aspernatur quam, perspiciatis, ducimus delectus facere fugit ex ut magni deserunt dignissimos quo nemo, repellendus veniam. Excepturi ipsum dolor sunt reprehenderit. Delectus aut doloribus voluptates minus possimus in architecto accusantium omnis excepturi dolorum quod, nihil dignissimos iste, a exercitationem quaerat. Enim deleniti placeat, error eius esse iusto? Facilis aperiam a iusto fuga! Unde, dolor maiores mollitia asperiores quis commodi voluptas exercitationem iste, aperiam nostrum, similique ratione nihil eum culpa. Iure magnam reprehenderit mollitia quam, itaque eum ipsa temporibus dolorem quod maiores delectus voluptas omnis neque reiciendis consequuntur voluptatibus aliquam, nam corporis odit laudantium, pariatur doloribus! Nesciunt, aperiam unde accusantium esse commodi velit neque reprehenderit blanditiis optio doloribus repellendus labore, quos eveniet laboriosam sapiente tenetur nobis provident, pariatur animi quas laudantium perspiciatis? Ea, quam dignissimos optio ab maiores quaerat esse est omnis consequatur ut repellendus, possimus quod, dolore iure repellat corporis vero voluptatum vitae. Quas porro exercitationem alias veritatis officia architecto consequatur? 
    </div>
  )
}

export default ProductPageSlider